### PR TITLE
Update to new timer API (>=4.15)

### PR DESCRIPTION
**Pull request by the-kennedys**
Fixed in Dark Star Breweries while setting up for Spin Up in A Brewery 2018.
Needs a quick verification test - it builds but I don't have a controller here.

### CODE REVIEW

**Comment by micolous** [comment]
Thanks for the patch!

Unfortunately, I can't test this either, as I misplaced my receiver about 2 years ago, and I haven't found it... :(

As is, this patch will break compatibility with <4.15 kernels, so I'll need to pop in some ifdefs for the older kernels (eg: Debian stable is on 4.9).

**Comment by the-kennedys** [comment]
So just wrap the change with 
`#if LINUX_VERSION_CODE >= KERNEL_VERSION(4, 15, 0)`
and otherwise support the old version? 
I'll sort it later, and maybe spin up an earlier vm to test it.

**Comment by the-kennedys** [comment]
Verified on ubuntu 3.13 and fedora 4.16 kernels - builds and installs. Not tested yet with real device.

**Comment by the-kennedys** [comment]
Tested final version against 4.16 kernel with real device using jstest.

**Comment by micolous** [comment]
Alright, I'll take your word for it :)

**Pull request merged**
